#!/bin/tcsh -xef

echo "auto-generated by afni_proc.py, Mon Sep 28 10:01:42 2026"
echo "(version 7.90, April 24, 2025)"
echo "execution started: `date`"

# to execute via tcsh: 
#   tcsh -xef /cbica/projects/nbthetaconn/nbthetaconn/data/001/code/001_ses-04_task-rest_mni_noclean.me.proc.csh |& tee /cbica/projects/nbthetaconn/nbthetaconn/data/001/code/output.001_ses-04_task-rest_mni_noclean.me.proc.csh
# to execute via bash: 
#   tcsh -xef /cbica/projects/nbthetaconn/nbthetaconn/data/001/code/001_ses-04_task-rest_mni_noclean.me.proc.csh 2>&1 | tee /cbica/projects/nbthetaconn/nbthetaconn/data/001/code/output.001_ses-04_task-rest_mni_noclean.me.proc.csh

# =========================== auto block: setup ============================
# script setup

# take note of the AFNI version
afni -ver

# check that the current AFNI version is recent enough
afni_history -check_date 24 Apr 2025
if ( $status ) then
    echo "** this script requires newer AFNI binaries (than 24 Apr 2025)"
    echo "   (consider: @update.afni.binaries -defaults)"
    exit
endif

# will run external programs, so be sure they are in PATH
which tedana
if ( $status ) then
   echo '** missing required external program: tedana'
   echo '   (perhaps a conda environment is needed)'
   exit 1
endif

# the user may specify a single subject to run with
if ( $#argv > 0 ) then
    set subj = $argv[1]
else
    set subj = 001_ses-04
endif

# assign output directory name
set output_dir = /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/001_ses-04_task-rest_mni_noclean.delete

# verify that the results directory does not yet exist
if ( -d $output_dir ) then
    echo output dir "$subj.results" already exists
    exit
endif

# set list of runs
set runs = (`count_afni -digits 2 1 2`)

# note 3 echoes and registration echo index
set echo_list = (`count_afni -digits 2 1 3`)
set echo_times = ( 13.4 31.12 48.84 )
set fave_echo = '02'

# create results and stimuli directories
mkdir -p $output_dir
mkdir $output_dir/stimuli

# copy anatomy to results dir
3dcopy                                                                            \
    /cbica/projects/nbthetaconn/nbthetaconn/data/001/anat/001_T1fs_conform.nii.gz \
    $output_dir/001_T1fs_conform

# copy template to results dir (for QC)
3dcopy /cbica/software/external/afni/17.2.10/MNI152_2009_template.nii.gz \
    $output_dir/MNI152_2009_template.nii.gz

# copy any -ROI_import datasets as ROI_import_LABEL
3dcopy /cbica/projects/nbthetaconn/software/afni/APQC_atlas_MNI.nii.gz \
    $output_dir/ROI_import_MNI

# ============================ auto block: tcat ============================
# apply 3dTcat to copy input dsets to results dir,
# while removing the first 4 TRs

# EPI runs for echo 1 (registration follower)
3dTcat -prefix $output_dir/pb00.$subj.r01.e01.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e1.nii'[4..$]'
3dTcat -prefix $output_dir/pb00.$subj.r02.e01.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e1.nii'[4..$]'


# EPI runs for echo 2 (fave_echo = registration driver)
3dTcat -prefix $output_dir/pb00.$subj.r01.e02.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e2.nii'[4..$]'
3dTcat -prefix $output_dir/pb00.$subj.r02.e02.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e2.nii'[4..$]'


# EPI runs for echo 3 (registration follower)
3dTcat -prefix $output_dir/pb00.$subj.r01.e03.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e3.nii'[4..$]'
3dTcat -prefix $output_dir/pb00.$subj.r02.e03.tcat     \
    /gpfs/fs001/cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e3.nii'[4..$]'


# and make note of repetitions (TRs) per run
set tr_counts = ( 446 446 )

# -------------------------------------------------------
# enter the results directory (can begin processing data)
cd $output_dir


# ---------------------------------------------------------
# QC: compute correlations with spherical ~averages
@radial_correlate -nfirst 0 -polort 3 -do_clean yes    \
                  -rdir radcor.pb00.tcat               \
                  pb00.$subj.r*.e$fave_echo.tcat+orig.HEAD

# ---------------------------------------------------------
# QC: look for columns of high variance
find_variance_lines.tcsh -polort 3                     \
       -rdir vlines.pb00.tcat                          \
       pb00.$subj.r*.e$fave_echo.tcat+orig.HEAD |& tee \
       out.vlines.pb00.tcat.txt

# ========================== auto block: outcount ==========================
# QC: compute outlier fraction for each volume
touch out.pre_ss_warn.txt
foreach run ( $runs )
    3dToutcount -automask -fraction -polort 3 -legendre                     \
                pb00.$subj.r$run.e$fave_echo.tcat+orig > outcount.r$run.1D

    # censor outlier TRs per run, ignoring the first 0 TRs
    # - censor when more than 0.15 of automask voxels are outliers
    # - step() defines which TRs to remove via censoring
    1deval -a outcount.r$run.1D -expr "1-step(a-0.15)" > rm.out.cen.r$run.1D

    # outliers at TR 0 might suggest pre-steady state TRs
    if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
        echo "** TR #0 outliers: possible pre-steady state TRs in run $run" \
            >> out.pre_ss_warn.txt
    endif
end

# catenate outlier counts into a single time series
cat outcount.r*.1D > outcount_rall.1D

# catenate outlier censor files into a single time series
cat rm.out.cen.r*.1D > outcount_${subj}_censor.1D

# ---------------------------------------------------------
# check for potential 4095 saturation issues
foreach run ( $runs )
    3dTto1D -method 4095_warn -input pb00.$subj.r$run.e$fave_echo.tcat+orig \
            |& tee -a out.4095_all.txt
end

# make a file showing any resulting warnings
awk '/warning/ {print}' out.4095_all.txt | tee out.4095_warn.txt

# get run number and TR index for minimum outlier volume
set minindex = `3dTstat -argmin -prefix - outcount_rall.1D\'`
set ovals = ( `1d_tool.py -set_run_lengths $tr_counts                       \
                          -index_to_run_tr $minindex` )
# save run and TR indices for extraction of vr_base_min_outlier
set minoutrun = $ovals[1]
set minouttr  = $ovals[2]
echo "min outlier: run $minoutrun, TR $minouttr" | tee out.min_outlier.txt

# ================================ despike =================================
# apply 3dDespike to each run
foreach run ( $runs )
    foreach eind ( $echo_list )
        3dDespike -NEW -nomask -prefix pb01.$subj.r$run.e$eind.despike \
            pb00.$subj.r$run.e$eind.tcat+orig
    end
end

# ================================= tshift =================================
# time shift data so all slice timing is the same 
foreach run ( $runs )
    foreach eind ( $echo_list )
        3dTshift -tzero 0 -quintic -prefix pb02.$subj.r$run.e$eind.tshift \
                 pb01.$subj.r$run.e$eind.despike+orig
    end
end

# --------------------------------
# extract volreg registration base
3dbucket -prefix vr_base_min_outlier                                      \
    pb02.$subj.r$minoutrun.e$fave_echo.tshift+orig"[$minouttr]"

# ================================= align ==================================
# for e2a: compute anat alignment transformation to EPI registration base
# (new anat will be intermediate, stripped, 001_T1fs_conform_ns+orig)
align_epi_anat.py -anat2epi -anat 001_T1fs_conform+orig \
       -save_skullstrip -suffix _al_junk                \
       -epi vr_base_min_outlier+orig -epi_base 0        \
       -epi_strip 3dAutomask                            \
       -cost lpc+ZZ -giant_move -check_flip             \
       -volreg off -tshift off

# ================================== tlrc ==================================
# warp anatomy to standard space (non-linear warp)
auto_warp.py -base MNI152_2009_template.nii.gz -input \
             001_T1fs_conform_ns+orig                 \
             -skull_strip_input no

# move results up out of the awpy directory
# - NL-warped anat, affine warp, NL warp
# - use typical standard space name for anat
# - wildcard is a cheap way to go after any .gz
# - be sure NIFTI sform_code=2 means standard space
3dbucket -DAFNI_NIFTI_VIEW=tlrc                       \
         -prefix 001_T1fs_conform_ns awpy/001_T1fs_conform_ns.aw.nii*
mv awpy/anat.un.aff.Xat.1D .
mv awpy/anat.un.aff.qw_WARP.nii .

# ================================= volreg =================================
# align each dset to base volume, to anat, warp to tlrc space

# verify that we have a +tlrc warp dataset
if ( ! -f 001_T1fs_conform_ns+tlrc.HEAD ) then
    echo "** missing +tlrc warp dataset: 001_T1fs_conform_ns+tlrc.HEAD" 
    exit
endif

# register and warp
foreach run ( $runs )
    # register each volume to the base image
    # (registration is driven by $fave_echo)
    3dvolreg -verbose -zpad 1 -base vr_base_min_outlier+orig                  \
             -1Dfile dfile.r$run.1D -prefix rm.epi.volreg.r$run.e$fave_echo   \
             -cubic                                                           \
             -1Dmatrix_save mat.r$run.vr.aff12.1D                             \
             pb02.$subj.r$run.e$fave_echo.tshift+orig

    # create an all-1 dataset to mask the extents of the warp
    3dcalc -overwrite -a pb02.$subj.r$run.e$fave_echo.tshift+orig -expr 1     \
           -prefix rm.epi.all1

    # catenate volreg/epi2anat/tlrc xforms
    cat_matvec -ONELINE                                                       \
               anat.un.aff.Xat.1D                                             \
               001_T1fs_conform_al_junk_mat.aff12.1D -I                       \
               mat.r$run.vr.aff12.1D > mat.r$run.warp.aff12.1D

    # apply catenated xform: volreg/epi2anat/tlrc/NLtlrc
    # (apply warps per echo - warps are fixed, per run)
    foreach eind ( $echo_list )
       3dNwarpApply -master 001_T1fs_conform_ns+tlrc -dxyz 2                  \
                    -source pb02.$subj.r$run.e$eind.tshift+orig               \
                    -nwarp "anat.un.aff.qw_WARP.nii mat.r$run.warp.aff12.1D"  \
                    -prefix rm.epi.nomask.r$run.e$eind
    end

    # warp the all-1 dataset for extents masking 
    3dNwarpApply -master 001_T1fs_conform_ns+tlrc -dxyz 2                     \
                 -source rm.epi.all1+orig                                     \
                 -nwarp "anat.un.aff.qw_WARP.nii mat.r$run.warp.aff12.1D"     \
                 -interp cubic                                                \
                 -ainterp NN -quiet                                           \
                 -prefix rm.epi.1.r$run

    # make an extents intersection mask of this run
    3dTstat -min -prefix rm.epi.min.r$run rm.epi.1.r$run+tlrc
end

# make a single file of registration params
cat dfile.r*.1D > dfile_rall.1D

# ----------------------------------------
# create the extents mask: mask_epi_extents+tlrc
# (this is a mask of voxels that have valid data at every TR)
3dMean -datum short -prefix rm.epi.mean rm.epi.min.r*.HEAD 
3dcalc -a rm.epi.mean+tlrc -expr 'step(a-0.999)' -prefix mask_epi_extents

# and apply the extents mask to the EPI data 
# (delete any time series with missing data)
foreach run ( $runs )
    foreach eind ( $echo_list )
        3dcalc -a rm.epi.nomask.r$run.e$eind+tlrc -b mask_epi_extents+tlrc    \
               -expr 'a*b' -prefix pb03.$subj.r$run.e$eind.volreg
    end
end

# warp the volreg base EPI dataset to make a final version
cat_matvec -ONELINE                                                           \
           anat.un.aff.Xat.1D                                                 \
           001_T1fs_conform_al_junk_mat.aff12.1D -I  > mat.basewarp.aff12.1D

3dNwarpApply -master 001_T1fs_conform_ns+tlrc -dxyz 2                         \
             -source vr_base_min_outlier+orig                                 \
             -nwarp "anat.un.aff.qw_WARP.nii mat.basewarp.aff12.1D"           \
             -prefix final_epi_vr_base_min_outlier

# create an anat_final dataset, aligned with stats
3dcopy 001_T1fs_conform_ns+tlrc anat_final.$subj

# record final registration costs
3dAllineate -base final_epi_vr_base_min_outlier+tlrc -allcostX                \
            -input anat_final.$subj+tlrc |& tee out.allcostX.txt

# -----------------------------------------
# warp anat follower datasets (non-linear)
# warp follower dataset 001_T1fs_conform+orig
3dNwarpApply -source 001_T1fs_conform+orig                                    \
             -master anat_final.$subj+tlrc                                    \
             -ainterp wsinc5 -nwarp anat.un.aff.qw_WARP.nii anat.un.aff.Xat.1D\
             -prefix anat_w_skull_warped

# ---------------------------------------------------------
# QC: compute correlations with spherical ~averages
@radial_correlate -nfirst 0 -polort 3 -do_clean yes                           \
                  -rdir radcor.pb03.volreg                                    \
                  pb03.$subj.r*.e$fave_echo.volreg+tlrc.HEAD

# ================================== mask ==================================
# create 'full_mask' dataset (union mask)
foreach run ( $runs )
    3dAutomask -prefix rm.mask_r$run pb03.$subj.r$run.e$fave_echo.volreg+tlrc
end

# create union of inputs, output type is byte
3dmask_tool -inputs rm.mask_r*+tlrc.HEAD -union -prefix full_mask.$subj

# ---- create subject anatomy mask, mask_anat.$subj+tlrc ----
#      (resampled from tlrc anat)
3dresample -master full_mask.$subj+tlrc -input 001_T1fs_conform_ns+tlrc \
           -prefix rm.resam.anat

# convert to binary anat mask; fill gaps and holes
3dmask_tool -dilate_input 5 -5 -fill_holes -input rm.resam.anat+tlrc    \
            -prefix mask_anat.$subj

# compute tighter EPI mask by intersecting with anat mask
3dmask_tool -input full_mask.$subj+tlrc mask_anat.$subj+tlrc            \
            -inter -prefix mask_epi_anat.$subj

# compute overlaps between anat and EPI masks
3dABoverlap -no_automask full_mask.$subj+tlrc mask_anat.$subj+tlrc      \
            |& tee out.mask_ae_overlap.txt

# note Dice coefficient of masks, as well
3ddot -dodice full_mask.$subj+tlrc mask_anat.$subj+tlrc                 \
      |& tee out.mask_ae_dice.txt

# ---- create group anatomy mask, mask_group+tlrc ----
#      (resampled from tlrc base anat, MNI152_2009_template.nii.gz)
3dresample -master mask_epi_anat.$subj+tlrc -prefix ./rm.resam.group    \
           -input                                                       \
           /cbica/software/external/afni/17.2.10/MNI152_2009_template.nii.gz'[0]'

# convert to binary group mask; fill gaps and holes
3dmask_tool -dilate_input 5 -5 -fill_holes -input rm.resam.group+tlrc   \
            -prefix mask_group

# note Dice coefficient of anat and template masks
3ddot -dodice mask_anat.$subj+tlrc mask_group+tlrc                      \
      |& tee out.mask_at_dice.txt

# ---- segment anatomy into classes CSF/GM/WM ----
3dSeg -anat anat_final.$subj+tlrc -mask AUTO -classes 'CSF ; GM ; WM'

# copy resulting Classes dataset to current directory
3dcopy Segsy/Classes+tlrc .

# make individual ROI masks for regression (CSF GM WM and CSFe GMe WMe)
foreach class ( CSF GM WM )
   # unitize and resample individual class mask from composite
   3dmask_tool -input Segsy/Classes+tlrc"<$class>"                      \
               -prefix rm.mask_${class}
   3dresample -master pb03.$subj.r01.e$eind.volreg+tlrc -rmode NN       \
              -input rm.mask_${class}+tlrc -prefix mask_${class}_resam
   # also, generate eroded masks
   3dmask_tool -input Segsy/Classes+tlrc"<$class>" -dilate_input -1     \
               -prefix rm.mask_${class}e
   3dresample -master pb03.$subj.r01.e$eind.volreg+tlrc -rmode NN       \
              -input rm.mask_${class}e+tlrc -prefix mask_${class}e_resam
end

# ================================ combine =================================
# combine multi-echo data per run, using method m_tedana
# (tedana from MEICA group)

# see also: https://tedana.readthedocs.io

# note the version of tedana (only capure stdout)
tedana --version | tee out.tedana_version.txt

# (get MEICA tedana final result, dn_ts_OC.nii.gz)

# first run tedana commands, to see if they all succeed
foreach run ( $runs )
   tedana -d pb03.$subj.r$run.e*.volreg+tlrc.HEAD     \
          -e $echo_times                              \
          --mask mask_epi_anat.$subj+tlrc.HEAD        \
          --out-dir tedana_r$run --convention orig
end

# now copy the tedana results
foreach run ( $runs )
   # copy, but get space/view from tedana input
   3dcalc -a pb03.$subj.r$run.e$fave_echo.volreg+tlrc \
          -b tedana_r$run/dn_ts_OC.nii.gz             \
          -prefix pb04.$subj.r$run.combine            \
          -expr b -datum float
end

# ================================== blur ==================================
# blur each volume of each run
foreach run ( $runs )
    3dBlurInMask -preserve -FWHM 4 -Mmask mask_epi_anat.$subj+tlrc \
                 -prefix pb05.$subj.r$run.blur                     \
                 pb04.$subj.r$run.combine+tlrc
end

# ================================= scale ==================================
# scale each voxel time series to have a mean of 100
# (be sure no negatives creep in)
# (subject to a range of [0,200])
foreach run ( $runs )
    3dTstat -prefix rm.mean_r$run pb05.$subj.r$run.blur+tlrc
    3dcalc -a pb05.$subj.r$run.blur+tlrc -b rm.mean_r$run+tlrc \
           -c mask_epi_anat.$subj+tlrc                         \
           -expr 'c * min(200, a/b*100)*step(a)*step(b)'       \
           -prefix pb06.$subj.r$run.scale
end

# ================================ regress =================================

# compute de-meaned motion parameters (for use in regression)
1d_tool.py -infile dfile_rall.1D -set_nruns 2                            \
           -demean -write motion_demean.1D

# compute motion parameter derivatives (for use in regression)
1d_tool.py -infile dfile_rall.1D -set_nruns 2                            \
           -derivative -demean -write motion_deriv.1D

# convert motion parameters for per-run regression
1d_tool.py -infile motion_demean.1D -set_nruns 2                         \
           -split_into_pad_runs mot_demean

1d_tool.py -infile motion_deriv.1D -set_nruns 2                          \
           -split_into_pad_runs mot_deriv

# create censor file motion_${subj}_censor.1D, for censoring motion 
1d_tool.py -infile dfile_rall.1D -set_nruns 2                            \
    -show_censor_count -censor_prev_TR                                   \
    -censor_motion 0.3 motion_${subj}

# combine multiple censor files
1deval -a motion_${subj}_censor.1D -b outcount_${subj}_censor.1D         \
       -expr "a*b" > censor_${subj}_combined_2.1D

# resample any -ROI_import dataset onto the EPI grid
# (and copy its labeltable)

3dresample -master final_epi_vr_base_min_outlier+tlrc -rmode NN          \
           -input ROI_import_MNI+tlrc                                    \
           -prefix ROI_import_MNI_resam

3drefit -copytables ROI_import_MNI+tlrc ROI_import_MNI_resam+tlrc
3drefit -cmap INT_CMAP ROI_import_MNI_resam+tlrc

# note TRs that were not censored
# (apply from a text file, in case of a lot of censoring)
1d_tool.py -infile censor_${subj}_combined_2.1D                          \
           -show_trs_uncensored space                                    \
           > out.keep_trs_rall.txt
set ktrs = "1dcat out.keep_trs_rall.txt"

# ------------------------------
# create ROI PC ort sets: WMe, CSFe, brain

# create a time series dataset to run 3dpc on...

# detrend, so principal components are not affected
foreach run ( $runs )
    # to censor, create per-run censor files
    1d_tool.py -set_run_lengths $tr_counts -select_runs $run             \
               -infile censor_${subj}_combined_2.1D -write rm.censor.r$run.1D

    # do not let censored time points affect detrending
    3dTproject -polort 3 -prefix rm.det_pcin_r$run                       \
               -censor rm.censor.r$run.1D -cenmode KILL                  \
               -input pb04.$subj.r$run.combine+tlrc
end

# catenate runs, prepare to censor TRs
3dTcat -prefix rm.det_pcin_rall rm.det_pcin_r*+tlrc.HEAD

# make ROI PCs : WMe
3dpc -mask mask_WMe_resam+tlrc -pcsave 1                                 \
     -prefix rm.ROIPC.WMe rm.det_pcin_rall+tlrc

# zero pad censored TRs
1d_tool.py -censor_fill_parent censor_${subj}_combined_2.1D              \
    -infile rm.ROIPC.WMe_vec.1D                                          \
    -write ROIPC.WMe.1D

# make ROI PCs : CSFe
3dpc -mask mask_CSFe_resam+tlrc -pcsave 1                                \
     -prefix rm.ROIPC.CSFe rm.det_pcin_rall+tlrc

# zero pad censored TRs
1d_tool.py -censor_fill_parent censor_${subj}_combined_2.1D              \
    -infile rm.ROIPC.CSFe_vec.1D                                         \
    -write ROIPC.CSFe.1D

# make ROI PCs : brain
3dpc -mask mask_epi_anat.$subj+tlrc -pcsave 1                            \
     -prefix rm.ROIPC.brain rm.det_pcin_rall+tlrc

# zero pad censored TRs
1d_tool.py -censor_fill_parent censor_${subj}_combined_2.1D              \
    -infile rm.ROIPC.brain_vec.1D                                        \
    -write ROIPC.brain.1D

# ------------------------------
# run the regression analysis
3dDeconvolve -input pb06.$subj.r*.scale+tlrc.HEAD                        \
    -mask mask_epi_anat.$subj+tlrc                                       \
    -censor censor_${subj}_combined_2.1D                                 \
    -ortvec ROIPC.WMe.1D ROIPC.WMe                                       \
    -ortvec ROIPC.CSFe.1D ROIPC.CSFe                                     \
    -ortvec ROIPC.brain.1D ROIPC.brain                                   \
    -ortvec mot_demean.r01.1D mot_demean_r01                             \
    -ortvec mot_demean.r02.1D mot_demean_r02                             \
    -ortvec mot_deriv.r01.1D mot_deriv_r01                               \
    -ortvec mot_deriv.r02.1D mot_deriv_r02                               \
    -polort 3                                                            \
    -num_stimts 0                                                        \
    -GOFORIT 10                                                          \
    -jobs 8                                                              \
    -fout -tout -x1D X.xmat.1D -xjpeg X.jpg                              \
    -x1D_uncensored X.nocensor.xmat.1D                                   \
    -fitts fitts.$subj                                                   \
    -errts errts.${subj}                                                 \
    -x1D_stop                                                            \
    -bucket stats.$subj

# -- use 3dTproject to project out regression matrix --
#    (make errts like 3dDeconvolve, but more quickly)
3dTproject -polort 0 -input pb06.$subj.r*.scale+tlrc.HEAD                \
           -mask mask_epi_anat.$subj+tlrc                                \
           -censor censor_${subj}_combined_2.1D -cenmode ZERO            \
           -ort X.nocensor.xmat.1D -prefix errts.${subj}.tproject



# if 3dDeconvolve fails, terminate the script
if ( $status != 0 ) then
    echo '---------------------------------------'
    echo '** 3dDeconvolve error, failing...'
    echo '   (consider the file 3dDeconvolve.err)'
    exit
endif


# display any large pairwise correlations from the X-matrix
1d_tool.py -show_cormat_warnings -infile X.xmat.1D |& tee out.cormat_warn.txt

# display degrees of freedom info from X-matrix
1d_tool.py -show_df_info -infile X.xmat.1D |& tee out.df_info.txt

# create an all_runs dataset to match the fitts, errts, etc.
3dTcat -prefix all_runs.$subj pb06.$subj.r*.scale+tlrc.HEAD

# --------------------------------------------------
# create a temporal signal to noise ratio dataset 
#    signal: if 'scale' block, mean should be 100
#    noise : compute standard deviation of errts
3dTstat -mean -prefix rm.signal.all all_runs.$subj+tlrc"[$ktrs]"
3dTstat -stdev -prefix rm.noise.all errts.${subj}.tproject+tlrc"[$ktrs]"
3dcalc -a rm.signal.all+tlrc                                             \
       -b rm.noise.all+tlrc                                              \
       -expr 'a/b' -prefix TSNR.$subj


# --------------------------------------------------
# compute TSNR stats for dset labels: brain, MNI

compute_ROI_stats.tcsh                                                   \
    -out_dir    tsnr_stats_regress                                       \
    -stats_file tsnr_stats_regress/stats_auto_brain.txt                  \
    -dset_ROI   mask_epi_anat.$subj+tlrc                                 \
    -dset_data  TSNR.$subj+tlrc                                          \
    -rset_label brain                                                    \
    -rval_list  1

compute_ROI_stats.tcsh                                                   \
    -out_dir    tsnr_stats_regress                                       \
    -stats_file tsnr_stats_regress/stats_auto_MNI.txt                    \
    -dset_ROI   ROI_import_MNI_resam+tlrc                                \
    -dset_data  TSNR.$subj+tlrc                                          \
    -rset_label MNI                                                      \
    -rval_list  ALL_LT

# ---------------------------------------------------
# compute and store GCOR (global correlation average)
# (sum of squares of global mean of unit errts)
3dTnorm -norm2 -prefix rm.errts.unit errts.${subj}.tproject+tlrc
3dmaskave -quiet -mask mask_epi_anat.$subj+tlrc                          \
          rm.errts.unit+tlrc > mean.errts.unit.1D
3dTstat -sos -prefix - mean.errts.unit.1D\' > out.gcor.1D
echo "-- GCOR = `cat out.gcor.1D`"

# ---------------------------------------------------
# compute correlation volume
# (per voxel: correlation with masked brain average)
3dmaskave -quiet -mask mask_epi_anat.$subj+tlrc                          \
          errts.${subj}.tproject+tlrc > mean.errts.1D
3dTcorr1D -prefix corr_brain errts.${subj}.tproject+tlrc mean.errts.1D

# --------------------------------------------------
# compute sum of baseline (all) regressors
3dTstat -sum -prefix sum_baseline.1D X.nocensor.xmat.1D

# ============================ blur estimation =============================
# compute blur estimates
touch blur_est.$subj.1D   # start with empty file

# create directory for ACF curve files
mkdir files_ACF

# -- estimate blur for each run in epits --
touch blur.epits.1D

# restrict to uncensored TRs, per run
foreach run ( $runs )
    set trs = `1d_tool.py -infile X.xmat.1D -show_trs_uncensored encoded \
                          -show_trs_run $run`
    if ( $trs == "" ) continue
    3dFWHMx -detrend -mask mask_epi_anat.$subj+tlrc                      \
            -ACF files_ACF/out.3dFWHMx.ACF.epits.r$run.1D                \
            all_runs.$subj+tlrc"[$trs]" >> blur.epits.1D
end

# compute average FWHM blur (from every other row) and append
set blurs = ( `3dTstat -mean -prefix - blur.epits.1D'{0..$(2)}'\'` )
echo average epits FWHM blurs: $blurs
echo "$blurs   # epits FWHM blur estimates" >> blur_est.$subj.1D

# compute average ACF blur (from every other row) and append
set blurs = ( `3dTstat -mean -prefix - blur.epits.1D'{1..$(2)}'\'` )
echo average epits ACF blurs: $blurs
echo "$blurs   # epits ACF blur estimates" >> blur_est.$subj.1D

# -- estimate blur for each run in errts --
touch blur.errts.1D

# restrict to uncensored TRs, per run
foreach run ( $runs )
    set trs = `1d_tool.py -infile X.xmat.1D -show_trs_uncensored encoded \
                          -show_trs_run $run`
    if ( $trs == "" ) continue
    3dFWHMx -detrend -mask mask_epi_anat.$subj+tlrc                      \
            -ACF files_ACF/out.3dFWHMx.ACF.errts.r$run.1D                \
            errts.${subj}.tproject+tlrc"[$trs]" >> blur.errts.1D
end

# compute average FWHM blur (from every other row) and append
set blurs = ( `3dTstat -mean -prefix - blur.errts.1D'{0..$(2)}'\'` )
echo average errts FWHM blurs: $blurs
echo "$blurs   # errts FWHM blur estimates" >> blur_est.$subj.1D

# compute average ACF blur (from every other row) and append
set blurs = ( `3dTstat -mean -prefix - blur.errts.1D'{1..$(2)}'\'` )
echo average errts ACF blurs: $blurs
echo "$blurs   # errts ACF blur estimates" >> blur_est.$subj.1D


# ========================= auto block: QC_review ==========================
# generate quality control review scripts and HTML report

# generate a review script for the unprocessed EPI data
# (all echoes of all runs)
gen_epi_review.py -script @epi_review.$subj \
    -dsets pb00.$subj.r*.e*.tcat+orig.HEAD

# -------------------------------------------------
# generate scripts to review single subject results
# (try with defaults, but do not allow bad exit status)

# write AP uvars into a simple txt file
cat << EOF > out.ap_uvars.txt
  mot_limit          : 0.3
  out_limit          : 0.15
  copy_anat          : 001_T1fs_conform+orig.HEAD
  combine_method     : m_tedana
  errts_dset         : errts.${subj}.tproject+tlrc.HEAD
  mask_dset          : mask_epi_anat.$subj+tlrc.HEAD
  template           : MNI152_2009_template.nii.gz
  ss_review_dset     : out.ss_review.$subj.txt
  echo_times         : 13.4 31.12 48.84
  max_4095_warn_dset : out.4095_warn.txt
  reg_echo           : 2
  vlines_tcat_dir    : vlines.pb00.tcat
EOF

# and convert the txt format to JSON
cat out.ap_uvars.txt | afni_python_wrapper.py -eval "data_file_to_json()" \
  > out.ap_uvars.json

# initialize gen_ss_review_scripts.py with out.ap_uvars.json
gen_ss_review_scripts.py -exit0        \
    -init_uvars_json out.ap_uvars.json \
    -write_uvars_json out.ss_review_uvars.json

# ========================== auto block: finalize ==========================

# remove temporary files
\rm -fr rm.* awpy Segsy

# --------------------------------------------------
# if the basic subject review script is here, run it
# (want this to be the last text output)
if ( -e @ss_review_basic ) then
    ./@ss_review_basic |& tee out.ss_review.$subj.txt

    # generate html ss review pages
    # (akin to static images from running @ss_review_driver)
    apqc_make_tcsh.py -review_style pythonic -subj_dir . \
        -uvar_json out.ss_review_uvars.json
    apqc_make_html.py -qc_dir QC_$subj

    echo "\nconsider running: \n"
    echo "   afni_open -b /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/001_ses-04_task-rest_mni_noclean.delete/QC_$subj/index.html"
    echo ""
endif

# return to parent directory (just in case...)
cd ..

echo "execution finished: `date`"




# ==========================================================================
# script generated by the command:
#
# afni_proc.py -script                                                                                         \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/code/001_ses-04_task-rest_mni_noclean.me.proc.csh       \
#     -scr_overwrite -subj_id 001_ses-04 -out_dir                                                              \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/001_ses-04_task-rest_mni_noclean.delete          \
#     -blocks despike tshift align tlrc volreg mask combine blur scale                                         \
#     regress -radial_correlate_blocks tcat volreg -anat_has_skull yes                                         \
#     -tcat_remove_first_trs 4 -align_opts_aea -cost lpc+ZZ -giant_move                                        \
#     -check_flip -tlrc_base MNI152_2009_template.nii.gz -tlrc_NL_warp                                         \
#     -copy_anat                                                                                               \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/anat/001_T1fs_conform.nii.gz                            \
#     -volreg_align_to MIN_OUTLIER -volreg_align_e2a -volreg_tlrc_warp                                         \
#     -mask_epi_anat yes -dsets_me_run                                                                         \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e1.nii \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e2.nii \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-01_MB6_TE3_bold_dir-ap_e3.nii \
#     -dsets_me_run                                                                                            \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e1.nii \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e2.nii \
#     /cbica/projects/nbthetaconn/nbthetaconn/data/001/ses-04/func_task-rest_run-02_MB6_TE3_bold_dir-ap_e3.nii \
#     -echo_times 13.4 31.12 48.84 -combine_method m_tedana -reg_echo 2                                        \
#     -blur_in_mask yes -blur_size 4 -mask_segment_anat yes                                                    \
#     -mask_segment_erode yes -regress_motion_per_run                                                          \
#     -regress_apply_mot_types demean deriv -regress_ROI_PC WMe 1                                              \
#     -regress_ROI_PC CSFe 1 -regress_ROI_PC brain 1 -regress_censor_motion                                    \
#     0.3 -regress_censor_outliers 0.15 -regress_apply_mask                                                    \
#     -regress_run_clustsim no -regress_opts_3dD -GOFORIT 10 -jobs 8                                           \
#     -regress_est_blur_epits -regress_est_blur_errts -test_stim_files no
